"""Country/team → flag emoji lookup. Fallback: empty string."""
from __future__ import annotations

_FLAGS: dict[str, str] = {
    # WM 2026 + häufige Nationen
    "algeria": "🇩🇿",
    "argentina": "🇦🇷",
    "australia": "🇦🇺",
    "austria": "🇦🇹",
    "belgium": "🇧🇪",
    "bolivia": "🇧🇴",
    "bosnia & herzegovina": "🇧🇦",
    "bosnia and herzegovina": "🇧🇦",
    "brazil": "🇧🇷",
    "cameroon": "🇨🇲",
    "canada": "🇨🇦",
    "cape verde": "🇨🇻",
    "chile": "🇨🇱",
    "china": "🇨🇳",
    "colombia": "🇨🇴",
    "costa rica": "🇨🇷",
    "croatia": "🇭🇷",
    "curaçao": "🇨🇼",
    "curacao": "🇨🇼",
    "czech republic": "🇨🇿",
    "czechia": "🇨🇿",
    "denmark": "🇩🇰",
    "dr congo": "🇨🇩",
    "ecuador": "🇪🇨",
    "egypt": "🇪🇬",
    "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "france": "🇫🇷",
    "germany": "🇩🇪",
    "ghana": "🇬🇭",
    "greece": "🇬🇷",
    "guinea": "🇬🇳",
    "haiti": "🇭🇹",
    "honduras": "🇭🇳",
    "hungary": "🇭🇺",
    "iran": "🇮🇷",
    "iraq": "🇮🇶",
    "ireland": "🇮🇪",
    "israel": "🇮🇱",
    "italy": "🇮🇹",
    "ivory coast": "🇨🇮",
    "côte d'ivoire": "🇨🇮",
    "jamaica": "🇯🇲",
    "japan": "🇯🇵",
    "jordan": "🇯🇴",
    "kenya": "🇰🇪",
    "malaysia": "🇲🇾",
    "mali": "🇲🇱",
    "mexico": "🇲🇽",
    "morocco": "🇲🇦",
    "netherlands": "🇳🇱",
    "new zealand": "🇳🇿",
    "nigeria": "🇳🇬",
    "north korea": "🇰🇵",
    "northern ireland": "🇬🇧",
    "norway": "🇳🇴",
    "panama": "🇵🇦",
    "paraguay": "🇵🇾",
    "peru": "🇵🇪",
    "poland": "🇵🇱",
    "portugal": "🇵🇹",
    "qatar": "🇶🇦",
    "republic of ireland": "🇮🇪",
    "romania": "🇷🇴",
    "russia": "🇷🇺",
    "saudi arabia": "🇸🇦",
    "scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "senegal": "🇸🇳",
    "serbia": "🇷🇸",
    "slovakia": "🇸🇰",
    "south africa": "🇿🇦",
    "south korea": "🇰🇷",
    "spain": "🇪🇸",
    "sweden": "🇸🇪",
    "switzerland": "🇨🇭",
    "tanzania": "🇹🇿",
    "thailand": "🇹🇭",
    "tunisia": "🇹🇳",
    "turkey": "🇹🇷",
    "türkiye": "🇹🇷",
    "ukraine": "🇺🇦",
    "uruguay": "🇺🇾",
    "usa": "🇺🇸",
    "united states": "🇺🇸",
    "uzbekistan": "🇺🇿",
    "venezuela": "🇻🇪",
    "vietnam": "🇻🇳",
    "wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "zambia": "🇿🇲",
    "zimbabwe": "🇿🇼",
}


def flag(team: str) -> str:
    """Return flag emoji for team name, or '' if unknown."""
    return _FLAGS.get(team.lower().strip(), "")


def with_flag(team: str) -> str:
    """Return 'Team 🇩🇪' or just 'Team' if no flag found."""
    f = flag(team)
    return f"{team} {f}".rstrip() if f else team
