"""Controlled producer for the operator-owned Top-5 runtime state."""

from __future__ import annotations

import os
from collections.abc import Mapping
from datetime import datetime, timezone
from pathlib import Path

from src.runtime.paths import governed_runtime_root
from src.utils.atomic_io import atomic_write_json

STATE_SCHEMA = "top5-governed-runtime-state-v1"
STATE_RELATIVE_PATH = "football/top5/governed-runtime/runtime-state-v1.json"


class GovernedRuntimeStateWriteError(ValueError):
    """Raised when a state write would violate the external-state contract."""


def write_governed_runtime_state(state: Mapping[str, object]) -> Path:
    """Atomically write state and generate observed_at internally.

    The caller supplies the observed runtime facts, but never the timestamp.
    The root is resolved through the governed external runtime convention and
    no provider, activation, publication, scheduler, betting, or ledger code
    is reachable from this writer.
    """

    if not isinstance(state, Mapping):
        raise GovernedRuntimeStateWriteError("runtime state must be a mapping")
    if "observed_at" in state:
        raise GovernedRuntimeStateWriteError("observed_at is generated by the state producer")

    root = governed_runtime_root()
    path = root / STATE_RELATIVE_PATH
    if path.is_symlink():
        raise GovernedRuntimeStateWriteError("runtime state must not be a symlink")
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    os.chmod(path.parent, 0o700)

    payload = dict(state)
    payload["schema_version"] = STATE_SCHEMA
    payload["runtime_root_role"] = "governed-runtime"
    payload["observed_at"] = datetime.now(timezone.utc).isoformat()
    atomic_write_json(path, payload, sort_keys=True)
    os.chmod(path, 0o600)
    return path


__all__ = ["STATE_SCHEMA", "STATE_RELATIVE_PATH", "write_governed_runtime_state"]
