"""Provider-neutral, append-only outcome-learning contracts.

This package is deliberately separate from betting, publication, provider
transport, and model activation.  It only validates immutable result and
prediction evidence and records their deterministic relationship.
"""

from .outcome_contracts import (
    ATTACHMENT_SCHEMA,
    AUTHORITATIVE_RESULT_SCHEMA,
    CAUSAL_TRAINING_ROW_SCHEMA,
    PREDICTION_SCHEMA,
    AppendOnlyOutcomeStore,
    AuthoritativeResultV1,
    CausalTrainingRowV1,
    InMemoryOutcomeStore,
    JsonlOutcomeStore,
    LifecycleError,
    OutcomeAttachmentV1,
    PredictionSnapshotV1,
    RetrainDecision,
    SettlementState,
    append_training_rows,
    build_outcome_attachment,
    canonical_digest,
    decide_retrain,
)
from .retrain_adapters import (
    BL2RetrainAdapter,
    Bundesliga2RetrainAdapter,
    GenericFootballRetrainAdapter,
    InternationalFootballRetrainAdapter,
    ModelFamilyRetrainAdapter,
    ModelFamilySpec,
    NationsLeagueRetrainAdapter,
    NLTreeCandidateRetrainAdapter,
    RetrainPlan,
    RetrainReceipt,
    TennisLGBMRetrainAdapter,
    TennisRetrainAdapter,
    Top5RetrainAdapter,
    ValidationReceipt,
    artifact_digest,
    authoritative_result_digest,
    build_default_adapters,
    feature_schema_digest,
    training_data_digest,
)

__all__ = [
    "ATTACHMENT_SCHEMA",
    "AUTHORITATIVE_RESULT_SCHEMA",
    "CAUSAL_TRAINING_ROW_SCHEMA",
    "PREDICTION_SCHEMA",
    "AppendOnlyOutcomeStore",
    "AuthoritativeResultV1",
    "BL2RetrainAdapter",
    "Bundesliga2RetrainAdapter",
    "CausalTrainingRowV1",
    "GenericFootballRetrainAdapter",
    "InMemoryOutcomeStore",
    "InternationalFootballRetrainAdapter",
    "JsonlOutcomeStore",
    "LifecycleError",
    "ModelFamilyRetrainAdapter",
    "ModelFamilySpec",
    "NLTreeCandidateRetrainAdapter",
    "NationsLeagueRetrainAdapter",
    "OutcomeAttachmentV1",
    "PredictionSnapshotV1",
    "RetrainDecision",
    "RetrainPlan",
    "RetrainReceipt",
    "SettlementState",
    "TennisLGBMRetrainAdapter",
    "TennisRetrainAdapter",
    "Top5RetrainAdapter",
    "ValidationReceipt",
    "append_training_rows",
    "artifact_digest",
    "authoritative_result_digest",
    "build_default_adapters",
    "build_outcome_attachment",
    "canonical_digest",
    "decide_retrain",
    "feature_schema_digest",
    "training_data_digest",
]
