#!/bin/bash
# Shared helper: pull --rebase before push to avoid race conditions
# between local cron jobs and GitHub Actions pushing to the same branch.
#
# Usage in a wrapper:
#   source scripts/_git_safe_push.sh
#   git_safe_push "<log_path>"
#
# Strategy:
#   - fetch + rebase with --strategy-option=theirs (remote wins for auto-generated files)
#   - if rebase still conflicts: abort cleanly + exit 1 (cron should not silently lose data)
#   - on push reject: 1 retry after second pull --rebase
#
# Note: --strategy-option=theirs means remote is preferred. For data files
# auto-generated by both local and CI (signals.json, odds_history.json, ledger.csv),
# the CI version is generally authoritative because it runs unconditionally
# even when MacBook is asleep.

git_safe_push() {
  local LOG="${1:-/dev/stderr}"
  local TS
  TS="$(date '+%Y-%m-%d %H:%M:%S %Z')"

  # 1. fetch latest remote
  git fetch origin main >> "$LOG" 2>&1

  # 2. rebase local commits onto origin/main
  if ! git pull --rebase --autostash --strategy-option=theirs origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: rebase conflict, aborting" >> "$LOG"
    git rebase --abort >> "$LOG" 2>&1 || true
    return 1
  fi

  # 3. push (first try)
  if git push origin main >> "$LOG" 2>&1; then
    return 0
  fi

  # 4. push rejected — race with another concurrent push. one more rebase + retry.
  echo "[$TS] git_safe_push: first push rejected, retrying after rebase" >> "$LOG"
  git fetch origin main >> "$LOG" 2>&1
  if ! git pull --rebase --autostash --strategy-option=theirs origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: retry rebase conflict" >> "$LOG"
    git rebase --abort >> "$LOG" 2>&1 || true
    return 1
  fi

  if git push origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: push ok (attempt 2) — $(git log origin/main -1 --oneline 2>/dev/null)" >> "$LOG"
    return 0
  fi

  # 5. Final attempt — third concurrent job may have pushed in between
  echo "[$TS] git_safe_push: second push rejected, final attempt" >> "$LOG"
  git fetch origin main >> "$LOG" 2>&1
  if ! git pull --rebase --autostash --strategy-option=theirs origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: final rebase conflict" >> "$LOG"
    git rebase --abort >> "$LOG" 2>&1 || true
    return 1
  fi
  if git push origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: push ok (attempt 3) — $(git log origin/main -1 --oneline 2>/dev/null)" >> "$LOG"
    return 0
  fi

  echo "[$TS] git_safe_push: push FAILED after 3 attempts — $(git log origin/main -1 --oneline 2>/dev/null)" >> "$LOG"
  return 1
}
