#!/bin/bash
# Shared helper: pull --rebase before push to avoid race conditions
# between local cron jobs and GitHub Actions pushing to the same branch.
#
# Usage in a wrapper:
#   source scripts/_git_safe_push.sh
#   git_safe_push "<log_path>"
#
# Strategy:
#   - Acquire process-level lock (/tmp/sportsbrain_push.lock) so concurrent
#     local cron jobs are serialised instead of all racing to push at once.
#   - Inside the lock: fetch + rebase with --strategy-option=theirs, then push.
#   - 3 retries handle GH-Actions pushes that may arrive while we hold the lock.
#   - Lock timeout: 90 s (any push takes <30 s normally; 90 s is generous).
#
# Note: --strategy-option=theirs means remote is preferred. For data files
# auto-generated by both local and CI (signals.json, odds_history.json, ledger.csv),
# the CI version is generally authoritative because it runs unconditionally
# even when MacBook is asleep.

# Internal: the actual push logic (called while holding the process lock).
_git_safe_push_body() {
  local LOG="$1"
  local TS
  TS="$(date '+%Y-%m-%d %H:%M:%S %Z')"

  git fetch origin main >> "$LOG" 2>&1

  if ! git pull --rebase --autostash --strategy-option=theirs origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: rebase conflict, aborting" >> "$LOG"
    git rebase --abort >> "$LOG" 2>&1 || true
    return 1
  fi

  if git push origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: push ok (attempt 1) — $(git log origin/main -1 --oneline 2>/dev/null)" >> "$LOG"
    return 0
  fi

  echo "[$TS] git_safe_push: first push rejected, retrying" >> "$LOG"
  git fetch origin main >> "$LOG" 2>&1
  if ! git pull --rebase --autostash --strategy-option=theirs origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: retry rebase conflict" >> "$LOG"
    git rebase --abort >> "$LOG" 2>&1 || true
    return 1
  fi
  if git push origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: push ok (attempt 2) — $(git log origin/main -1 --oneline 2>/dev/null)" >> "$LOG"
    return 0
  fi

  echo "[$TS] git_safe_push: second push rejected, final attempt" >> "$LOG"
  git fetch origin main >> "$LOG" 2>&1
  if ! git pull --rebase --autostash --strategy-option=theirs origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: final rebase conflict" >> "$LOG"
    git rebase --abort >> "$LOG" 2>&1 || true
    return 1
  fi
  if git push origin main >> "$LOG" 2>&1; then
    echo "[$TS] git_safe_push: push ok (attempt 3) — $(git log origin/main -1 --oneline 2>/dev/null)" >> "$LOG"
    return 0
  fi

  echo "[$TS] git_safe_push: push FAILED after 3 attempts — HEAD=$(git log --oneline -1 2>/dev/null)" >> "$LOG"
  return 1
}

git_safe_push() {
  local LOG="${1:-/dev/stderr}"
  local LOCKFILE="/tmp/sportsbrain_push.lock"
  local TS
  TS="$(date '+%Y-%m-%d %H:%M:%S %Z')"

  if command -v flock >/dev/null 2>&1; then
    # flock available (Linux or macOS+Homebrew util-linux): exclusive lock, 90s timeout
    (
      flock -w 90 200 || {
        echo "[$TS] git_safe_push: lock timeout (flock)" >> "$LOG"
        exit 1
      }
      _git_safe_push_body "$LOG"
    ) 200>"$LOCKFILE"
    return $?
  else
    # mkdir-based spin lock — atomic on POSIX, portable macOS fallback
    local LOCKDIR="${LOCKFILE}.d"
    local waited=0
    while ! mkdir "$LOCKDIR" 2>/dev/null; do
      if [ $waited -ge 90 ]; then
        echo "[$TS] git_safe_push: lock timeout (mkdir)" >> "$LOG"
        return 1
      fi
      sleep 3
      waited=$((waited + 3))
    done
    echo $$ > "$LOCKDIR/pid"
    _git_safe_push_body "$LOG"
    local ret=$?
    rm -rf "$LOCKDIR"
    return $ret
  fi
}
